matchya/matchya

- matchya-web/src/components/Header.tsx
add navigation from header to setting and home
> navigate setting and home from header

- .gitignore
- lambdas/registrar/handler.py
- lambdas/registrar/package-lock.json
- lambdas/registrar/package.json
- lambdas/registrar/serverless.yml
- package-lock.json
- package.json
Set up basic backend structure. 
Includes:
- lambdas
- package.json for root third-party modules
> feat: set up root structure in repo

- .gitignore
- terraform/.terraform.lock.hcl
- terraform/provider.tf
Set up basic structure for terraform with aws provider info
> feat: set up basic structure of terraform

- .flake8
- .husky/pre-commit
- package-lock.json
- package.json
> feat: set up linting for lambdas so it follows consistency

- lambdas/generator/handler.py
- lambdas/generator/serverless.yml
Get company's GitHub URL from DB (but not using it for now because they are all fake)
store generated criteria to Criteria DB
> 41 feat store generated criteria in generator lambda

- lambdas/generator/handler.py
use string set for tech_stack field
rename variables and method according to the change in db schema
remove database process with dynamo
> use string set instead of list

- lambdas/authentication/config.py
- lambdas/authentication/login.py
- lambdas/authentication/register.py
- lambdas/authentication/requirements.txt
update authentication lambda (register and login) to use postgres db
environment variables are set on lambda's env vars
removed dynamo Company table
installed psycopg2-binary
> 71 feat hook up register endpoint with db

- web/package-lock.json
- web/package.json
- web/src/App.tsx
- web/src/components/Header/Header.tsx
- web/src/components/LoginModal/AuthModal.tsx
- web/src/screens/Dashboard/Dashboard.stories.tsx
- web/src/screens/Dashboard/Dashboard.tsx
- web/src/screens/Settings/Settings.tsx
- web/src/store/useAuthStore.ts
install Zustand
store access token when a user logs in and registers. (local storage and zustand store)
check access token using useEffect in App.tsx (not checking expiration)
Change Github Url to GitHub Username
Home Screen is named Dashboard
> 74 featui set up basic structure of global state management zustand

- lambdas/authentication/utils/response.py
- lambdas/criteria/Dockerfile
- lambdas/criteria/evaluate.py
- lambdas/criteria/generate.py
- lambdas/criteria/retrieve.py
- lambdas/criteria/utils/response.py
Change headers of lambda functions
> 85 feat enable cors for lambdas

- lambdas/criteria/evaluate.py
- lambdas/criteria/generate.py
- lambdas/criteria/retrieve.py
small PR
return error message using util method
> return error message in json with header

- web/src/screens/Dashboard/CriteriaBox.tsx
small PR
receive data as response.data.paylaod, not response.data
> 91 fixui recieve data as payload

- lambdas/authentication/login.py
- lambdas/authentication/register.py
Create Default Position "Software Engineer" when a user registers a new company.
organize login.py
> 98 feat create default position when a company registers

- lambdas/criteria/client/github.py
- lambdas/criteria/generate.py
Generate keywords and messages.
Updated prompt to create more accurate criteria
> 96 feat generate criteria sentence and keywords and return sentences

- lambdas/criteria/client/github.py
- lambdas/criteria/evaluate.py
- lambdas/criteria/generate.py
- lambdas/criteria/serverless.yml
Refactoring. 
separate methods, use github client methods.
handle errors
> 115 refactor cleanup criteria generator

- lambdas/criteria/config.py
- lambdas/criteria/generate.py
- lambdas/criteria/requirements.txt
get github_username from position_id given by request body.
store generated criteria into dynamodb
> 123 feat save generated criteria to dynamodb

- lambdas/authentication/login.py
- lambdas/authentication/register.py
- lambdas/authentication/utils/response.py
return correct error message
log requests
> 131 feat set up logger for login

- lambdas/authentication/login.py
- lambdas/authentication/register.py
- lambdas/criteria/client/github.py
- lambdas/criteria/generate.py
- lambdas/criteria/utils/response.py
> 144 feat set up logger for criteria generator

- lambdas/criteria/evaluate.py
> 146 feat set up logger for criteria evaluator

- db/changelog/01-create-tables.sql
- lambdas/authentication/register.py
- lambdas/authentication/requirements.txt
save company's repository names
created company_repository table
> 151 feat save companys repository names when it registers

- lambdas/company/Dockerfile
- lambdas/company/config.py
- lambdas/company/handler.py
- lambdas/company/requirements.txt
- lambdas/company/utils/request.py
- lambdas/company/utils/response.py
take a company with the info from db
> 155-feat-implement-company-lambda

- db/changelog/01-create-tables.sql
- lambdas/criteria/generate.py
- lambdas/position/handler.py
store repository names in position_repository
get the repository names from db when a user get a position
> 161 fix store repository info for criteria in postgres instread of dynamodb

- lambdas/criteria/retrieve.py
> fix retrieve criteria

- web/src/screens/Dashboard/AddCandidateModal.tsx
- web/src/screens/Dashboard/CriteriaBox.tsx
- web/src/screens/Dashboard/Dashboard.tsx
- web/src/screens/Dashboard/DashboardHeader.tsx
- web/src/screens/Dashboard/Sidebar.tsx
added a sidebar and the header on dashboard screen
> 165 featui create sidebar and header for positions on dashboard

- db/changelog/01-create-tables.sql
- lambdas/criteria/evaluate.py
- lambdas/criteria/generate.py
- lambdas/criteria/retrieve.py
- lambdas/position/handler.py
- terraform/environment/modules/dynamodb/main.tf
position can have many checklists
checklist can have many criteria
results are associated with checklists
> 170 feat redesign database so we can allow multiple checklist for one position

- lambdas/checklist/client/github.py
- lambdas/checklist/config.py
- lambdas/checklist/evaluate.py
- lambdas/checklist/publish_evaluation.py
- lambdas/checklist/serverless.yml
- lambdas/checklist/utils/response.py
set up the process through | http -> evaluation publisher -> SQS -> evaluator
validate the request body in the evaluation publisher so we evaluate the candidates successfully or return error immediately
> 190 feat set up lambda for evaluate http

- lambdas/company/handler.py
- lambdas/company/serverless.yml
> setup endpoint

- lambdas/position/handler.py
- web/src/components/LoginModal/ScoreCard.tsx
- web/src/screens/Dashboard/CriteriaBox.tsx
- web/src/screens/Dashboard/Dashboard.tsx
- web/src/screens/Dashboard/Sidebar.tsx
- web/src/types/index.ts
> 214 featui hook up retrieve position endpoint with UI

- lambdas/checklist/serverless.yml
- lambdas/position/handler.py
- web/src/screens/Dashboard/AddCandidateModal.tsx
- web/src/screens/Dashboard/CriteriaBox.tsx
- web/src/screens/Dashboard/Dashboard.tsx
- web/src/screens/Dashboard/DashboardHeader.tsx
> 88 featui hook up candidate evaluation endpoint with UI

- web/src/components/Header/Header.tsx
- web/src/screens/Dashboard/Dashboard.tsx
add dashboard button
manage login state on header file
> 228 featui add dashboard button on header

- lambdas/authentication/login.py
- lambdas/authentication/register.py
- web/src/screens/Login.tsx
- web/src/types/index.ts
return detailed error message when login/register fails
> 230 featui show detailed error message on login page

- web/src/components/Button.tsx
- web/src/components/ErrorToast.tsx
- web/src/components/FormInput.tsx
- web/src/components/ToastMessage.tsx
- web/src/screens/Dashboard/AddCandidateModal.tsx
- web/src/screens/Login.tsx
edit add candidate modal to show error/success messages, loading
> 232 fixui fix add candidate modal to restrict invalid inputs

- web/src/index.css
- web/src/screens/Dashboard/Dashboard.tsx
- web/src/screens/Dashboard/ScoreCard.tsx
scroll evaluated canddiates on dashboard
> scrollable cards

- lambdas/checklist/client/github.py
when a file is empty, no error should be thrown
> 237 fix evaluation processor gives error getting file content

- web/src/screens/Dashboard/AddCandidateModal.tsx
- web/src/screens/Dashboard/CriteriaBox.tsx
- web/src/screens/Dashboard/Dashboard.tsx
show loading spin and toast messages
> 239 featui show loading spin and message toast for generating checklist

- lambdas/checklist/evaluate.py
solved error when the same email is used to evaluate a candidate for different checklist
> candidate can apply multiple positions

- db/changelog/01-create-tables.sql
add column "checklist_generation_status" to position table
default: "unscheduled"
> updated db

- lambdas/position/checklist_status.py
- lambdas/position/retrieve.py
- lambdas/position/serverless.yml
create endpoint to fetch checklist status
> 250 feat set up endpoint to fetch checklist generation status

- lambdas/checklist/generate.py
- lambdas/checklist/publish_generation.py
update position's checklist status when checklist generation processor is done
> 254 feat update positions checklist status when generation is scheduled and actually done

- db/changelog/01-create-tables.sql
- lambdas/checklist/client/github.py
- lambdas/checklist/evaluate.py
- lambdas/checklist/utils/compression.py
add some parameters to OpenAI API
improved prompt
check consistency.
- Compression algorithm for each file types (as long as LLM can understand, reduce the token)
- Read more files from one repo (ask LLM to choose files to read)
> 261 feat improve evaluation algorithm and process

- lambdas/checklist/client/github.py
- lambdas/checklist/generate.py
- lambdas/checklist/utils/compression.py
implemented compression algorithms...
next -> read more files
> 264 feat compress files while reserving critical info to reduce tokens

- lambdas/position/retrieve.py
- web/src/screens/Dashboard/CriteriaBox/index.tsx
- web/src/screens/Dashboard/ScoreCard.tsx
- web/src/types/index.ts
> 285 feat display sorted criteria message for both checklist and candidate results

- lambdas/authentication/config.py
- lambdas/authentication/github.py
- lambdas/authentication/serverless.yml
- web/src/App.tsx
- web/src/components/ui/UserAuthForm/UserAuthForm.tsx
- web/src/config/env.ts
- web/src/screens/Authentication/GithubAuthCallback.tsx
implement github oauth
register / login
> 287 feat implement GitHub oauth and get repository access

- lambdas/authentication/github.py
- web/src/components/ui/UserAuthForm/UserAuthForm.tsx
#290 
change token scope
get all repositories including private ones
> Refactor user authentication

- db/changelog/01-create-tables.sql
- lambdas/authentication/config.py
- lambdas/authentication/github.py
- lambdas/authentication/requirements.txt
- lambdas/authentication/serverless.yml
- lambdas/authentication/utils/token.py
store github access token as encrypted value in db when user registers with GitHub
> Save github access token when registers

- lambdas/authentication/utils/token.py
- lambdas/checklist/client/github.py
- lambdas/checklist/config.py
- lambdas/checklist/evaluate.py
- lambdas/checklist/generate.py
- lambdas/checklist/requirements.txt
- lambdas/checklist/serverless.yml
- lambdas/checklist/utils/token.py
This pull request refactors the token encryption process and removes the decryption function from the authentication folder. It also adds the necessary dependencies to the requirements.txt file and creates a new token.py file for decrypting the GitHub access token.
> Refactor token encryption and remove decryption function from authentication folder

- lambdas/checklist/client/github.py
- lambdas/checklist/evaluate.py
- lambdas/checklist/generate.py
> 298 refactor type hinting for methods in checklist folder

- db/changelog/01-create-tables.sql
- lambdas/checklist/evaluate.py
- lambdas/checklist/publish_evaluation.py
- lambdas/checklist/serverless.yml
- lambdas/position/retrieve.py
add status column to candidate_result table
create new candidate and candidate result when evaluation_publisher is called
if previous evaluation has failed, update the candidate_result table.
return candidates with the status when retrieve position is called
> 300 feat setup backend process to let UI know which candidates are being evaluated

- web/src/components/ui/Dialog/CreatePositionDialog/CreatePositionDialog.tsx
- web/src/components/ui/Dialog/GenerateCriteriaDialog/GenerateCriteriaDialog.tsx
- web/src/components/ui/DropdownMenu/UserNavDropdownMenu/UserNavDropdownMenu.tsx
- web/src/components/ui/MainNav/MainNav.tsx
- web/src/components/ui/PositionSwitcher/PositionSwitcher.tsx
- web/src/components/ui/Sheet/ChecklistSheet/ChecklistSheet.tsx
- web/src/screens/Dashboard/AddCandidateModal.tsx
- web/src/screens/Dashboard/Dashboard.tsx
- web/src/screens/Dashboard/DashboardHeader.tsx
- web/src/screens/Dashboard/Sidebar.tsx
- web/src/store/useCompanyStore.ts
- web/src/store/usePositionStore.ts
- web/src/types/index.ts
> Update position-related imports and variables

- lambdas/position/retrieve.py
> add keywords in criteria for retrieving position

- web/src/components/ui/Table/ChecklistTable/ChecklistTable.tsx
- web/src/types/index.ts
issue #
show keywords on the ui
> Refactor ChecklistTable to use item keywords

- lambdas/checklist/client/github.py
> Fix error handling in GithubClient class

- web/src/components/ui/MainNav/MainNav.tsx
when generation faild, set button message as "Generation failed"
> Refactor MainNav component

- db/changelog/01-create-tables.sql
- lambdas/authentication/github.py
- lambdas/authentication/login.py
- lambdas/checklist/publish_evaluation.py
- lambdas/checklist/publish_generation.py
check if checklist already exist
> 317 feat save checklist generation status in checklist table by creating it in publisher

- lambdas/position/candidates_status.py
- lambdas/position/serverless.yml
- web/src/components/ui/MainNav/MainNav.tsx
- web/src/screens/Dashboard/CriteriaBox/ScheduledCriteriaBox.tsx
prepare candidates status api for polling evaluation status
> Add candidates_status lambda and update API paths

- lambdas/position/retrieve.py
- web/src/types/index.ts
> Add candidate ID to Candidate interface

- web/src/screens/Authentication/GithubAuthCallback.tsx
style github callback screen (simple)
> Add login failure handling and UI improvements to GithubAuthCallback.tsx

- lambdas/position/candidates.py
- lambdas/position/retrieve.py
- lambdas/position/serverless.yml
> 339 feat create get candidate endpoint for a position

- web/src/components/ui/Card/AllCandidatesCard/AllCandidatesCard.tsx
- web/src/components/ui/Card/CandidateDetailCard/CandidateDetailCard.tsx
- web/src/components/ui/Table/EvaluationTable/EvaluationTable.tsx
- web/src/screens/Dashboard/Dashboard.tsx
- web/src/store/usePositionStore.ts
- web/src/template/Dashboard.tsx
- web/src/types/index.ts
use template to display candidates on dashboard
> Refactor candidate status display in AllCandidatesCard and add null check in CandidateDetailCard

- lambdas/checklist/publish_evaluation.py
- web/src/components/ui/Card/AllCandidatesCard/AllCandidatesCard.tsx
- web/src/components/ui/MainNav/MainNav.tsx
show canddiate evaluation status
and implement retry evaluation
> Add selectedPosition to CandidateRow component

- web/src/components/ui/Card/AllCandidatesCard/AllCandidatesCard.tsx
- web/src/components/ui/MainNav/MainNav.tsx
- web/src/screens/Dashboard/Dashboard.tsx
- web/src/store/usePositionStore.ts
> Remove console.log statement in MainNav.tsx

- lambdas/checklist/publish_evaluation.py
- lambdas/position/candidates.py
- lambdas/position/retrieve.py
- web/src/components/ui/MainNav/MainNav.tsx
- web/src/screens/Dashboard/Dashboard.tsx
- web/src/types/index.ts
> Add created_at field to candidate_result table

- web/src/components/ui/Card/CandidateDetailCard/CandidateDetailCard.tsx
- web/src/screens/Dashboard/Dashboard.tsx
display empty candidate list when checklist hasn't been created
> Refactor candidate detail card and dashboard rendering

- web/src/components/ui/Dialog/AddCandidateDialog/AddCandidateDialog.tsx
- web/src/components/ui/Dialog/GenerateCriteriaDialog/GenerateCriteriaDialog.tsx
- web/src/components/ui/MainNav/MainNav.tsx
> Fix error handling and display error messages in dialogs

- web/src/App.tsx
- web/src/components/ui/Header/Header.tsx
- web/src/layout/AuthenticatedLayout.tsx
- web/src/layout/UnAuthenticatedLayout.tsx
authentication routing and headers
> 368 fix when the user is not authenticated user cant navigate to home page

- web/src/App.tsx
- web/src/components/DropdownMenu/UserNavDropdownMenu/UserNavDropdownMenu.tsx
> disabled settings page on web

- lambdas/authentication/github.py
- lambdas/checklist/client/github.py
- lambdas/checklist/generate.py
use full repository name with owner
e.g. "kokiebisu/matchya"
> Update repository names to use full names

- web/src/screens/AuthenticationPage.tsx
> Update redirect URI for GitHub login

- lambdas/authentication/serverless.yml
- lambdas/checklist/serverless.yml
- lambdas/company/serverless.yml
- lambdas/position/serverless.yml
> Update CORS origins in serverless.yml files

- lambdas/checklist/evaluate.py
- lambdas/checklist/generate.py
- lambdas/position/retrieve.py
- terraform/environment/modules/sqs/main.tf
fix errors caused by creating same assessment criteria twice
> Update candidate and checklist generation status

- lambdas/checklist/client/github.py
- lambdas/checklist/evaluate.py
- lambdas/checklist/publish_evaluation.py
- lambdas/position/candidates.py
read more information from repositories (commits, pull requests, contributors) to see how big the repo is.
read more repositories n=8
improve prompts
> feat(lambda): improve evaluation algorithm to give higher scores

- web/src/components/MainNav/MainNav.tsx
set open state for shecklist dialog
> feat(web): open checklist sheet when genration is done

- lambdas/authentication/google.py
- lambdas/authentication/serverless.yml
- web/src/screens/AuthenticationPage.tsx
implemented google login with python backend
> feat(authentication): implement google login backend

- lambdas/authentication/google.py
- lambdas/position/create.py
- lambdas/position/serverless.yml
- lambdas/position/utils/request.py
create new position (will be attached to UI)
> feat(position): implement api to create a position

- web/src/screens/DashboardPage.tsx
- web/src/template/PositionSetupPage/PositionSetup.stroies.tsx
- web/src/template/PositionSetupPage/PositionSetupPage.tsx
- web/src/template/index.ts
breifly create ui to connect to backend functionality
> feat(web): show position setup screen when user doesnt have a position

- db/changelog/01-create-tables.sql
- lambdas/authentication/github.py
- lambdas/authentication/google.py
- lambdas/position/create.py
> feat(position): modify position table so we can store the name the type and the level

- web/src/components/Card/AllCandidatesCard/AllCandidatesCard.tsx
- web/src/components/Card/CandidateDetailCard/CandidateDetailCard.tsx
> fix(web): fix floating point on candidate evaluate score

- db/changelog/01-create-tables.sql
> feat(db): organized liquibase changelogs

- lambdas/checklist/config.py
- lambdas/checklist/default_criteria.py
- lambdas/checklist/generate.py
- lambdas/checklist/publish_generation.py
- lambdas/position/create.py
- web/src/components/Dialog/GenerateCriteriaDialog/GenerateCriteriaDialog.tsx
generate a checklist with position type if no repository is selected
> feat(checklist) generate a checklist from a position name

- web/src/App.tsx
- web/src/components/MainNav/MainNav.tsx
- web/src/screens/AuthenticationPage.tsx
- web/src/screens/DashboardPage.tsx
- web/src/screens/GithubAuthCallbackPage.tsx
- web/src/screens/PositionSetupPage.tsx
- web/src/store/company.tsx
- web/src/store/position.tsx
- web/src/template/PositionSetupPage/PositionSetup.stories.tsx
- web/src/template/PositionSetupPage/PositionSetupPage.tsx
> feat(web): set up onboarding pages for GitHub login

- lambdas/checklist/generate.py
- web/src/screens/PositionSetupPage.tsx
- web/src/template/PositionSetupPage/PositionSetup.stories.tsx
- web/src/template/PositionSetupPage/PositionSetupPage.tsx
call checklist/generate after creating a position
> feat(web): generate checklist automatically after creating a position

- lambdas/position/retrieve.py
- lambdas/question/generate.py
> feat(position): retrieve generated questions from a position

- lambdas/question/generate.py
Don't use a checklist to generate questions.
Based on the position, pick keywords
> fix(question): generate question without using checklist keywords

- lambdas/authentication/github.py
- lambdas/authentication/google.py
create default (Software engineer, mid-level, fullstack)
> feat(authentication): create default position when a user registers

- lambdas/position/questions.py
- lambdas/position/serverless.yml
- lambdas/question/utils/response.py
retrieve questions by position id
> feat(question): retrieve questions by position

- db/changelog/01-create-tables.sql
- lambdas/checklist/generate.py
- lambdas/question/config.py
- lambdas/question/publish_generation.py
- lambdas/question/serverless.yml
> feat(question): create generation publisher for questions

- lambdas/authentication/serverless.yml
- web/src/screens/GithubAuthCallbackPage.tsx
- web/src/screens/GoogleAuthCallbackPage.tsx
> fix(authentication): change authentication api path

- db/changelog/01-create-tables.sql
- lambdas/candidate/.releaserc.json
- lambdas/candidate/Dockerfile
- lambdas/candidate/add.py
- lambdas/candidate/changelog.config.js
- lambdas/candidate/config.py
- lambdas/candidate/package-lock.json
- lambdas/candidate/package.json
- lambdas/candidate/requirements.txt
- lambdas/candidate/serverless.yml
- lambdas/candidate/utils/request.py
- lambdas/candidate/utils/response.py
- web/src/screens/GoogleAuthCallbackPage.tsx
created candidate lambda
- removed checklist lambda from aws
> feat(candidate) create candidate lambda and add candidate api

- db/changelog/01-create-tables.sql
- lambdas/authentication/github.py
- lambdas/question/generate.py
remove unnecessary tables, update some
> feat(db): setup database for mvp

- lambdas/position/candidates.py
- lambdas/position/serverless.yml
retrieve candidates by position
> feat(position): retrieve candidates by position

- lambdas/position/utils/response.py
- lambdas/question/utils/response.py
> chore(question): success resopnse with empty payload

- lambdas/position/candidates.py
> feat(position): attached candidate result id for retrieve candiates

- db/changelog/01-create-tables.sql
> fix(db): fix mistakes

- lambdas/authentication/github.py
- lambdas/authentication/google.py
> feat(authentication): do not create a new position on signup

- lambdas/company/handler.py
> fix(company): me does not return github usename and positions

- lambdas/candidate/add.py
- lambdas/candidate/utils/request.py
- lambdas/company/handler.py
- lambdas/company/utils/request.py
> feat(candidate): add and register a candidate to a company

- lambdas/candidate/retrieve.py
- lambdas/candidate/serverless.yml
> feat(candidate): Add retrieve candidate lambda function and serverless configuration

- lambdas/authentication/github.py
- lambdas/authorizer/config.py
- lambdas/company/me.py
- lambdas/company/serverless.yml
- lambdas/company/utils/request.py
fixed me and authorizor as well
> fix(authentication) do not save GitHub username

- lambdas/candidate/retrieve.py
> fix(candidate): Refactor candidate retrieval query to include company candidate join

- lambdas/question/generate.py
- lambdas/test/.releaserc.json
- lambdas/test/Dockerfile
- lambdas/test/changelog.config.js
- lambdas/test/config.py
- lambdas/test/create.py
- lambdas/test/package-lock.json
- lambdas/test/package.json
- lambdas/test/requirements.txt
- lambdas/test/serverless.yml
- lambdas/test/utils/request.py
- lambdas/test/utils/response.py
create test in test lambda
send message to the question generation sqs
generate questions and save them
> feat(test): create a test and questions for a company

- lambdas/test/retrieve.py
- lambdas/test/serverless.yml
> feat(test): get associated tests with a company

- lambdas/test/retrieve_by_id.py
- lambdas/test/serverless.yml
> feat(test): retrieve a test by test id with questions

- lambdas/question/audio_receiver.py
- lambdas/question/config.py
- lambdas/question/evaluate.py
- lambdas/question/package.json
- lambdas/question/serverless.yml
using whisper api
direct upload to s3 works, but audio receiver lambda not working now..
> feat(question): create s3 trigger and convert it to text

- lambdas/question/evaluate.py
- lambdas/question/serverless.yml
> feat(question): evaluate the text convereted from audio file and store the answer

- db/changelog/01-create-tables.sql
- lambdas/test/retrieve.py
created_at -> updated_at
num_candidates (result generated)
> feat(test): fix returning json for get tests request according to figma design

- lambdas/candidate/retrieve_result.py
- lambdas/candidate/serverless.yml
> feat(candidate): retrieve candidate result details

- lambdas/question/generate.py
- lambdas/question/utils/topics.py
- lambdas/test/retrieve_by_id.py
choose topics by positon type, level
> feat(question): choose question topics based on position level and type

- lambdas/authentication/github.py
- lambdas/authentication/google.py
- lambdas/authentication/logout.py
- lambdas/authentication/utils/company.py
- lambdas/authentication/utils/request.py
- lambdas/authentication/utils/token.py
> chore(authentication): clean up

- lambdas/question/evaluate.py
- lambdas/question/generate.py
- lambdas/question/utils/topics.py
> chore(question): clean up code

- lambdas/test/create.py
- lambdas/test/retrieve.py
- lambdas/test/retrieve_by_id.py
- lambdas/test/utils/request.py
> chore(test): clean up code in test lambda

- lambdas/candidate/add.py
- lambdas/candidate/evaluate.py
- lambdas/candidate/retrieve.py
- lambdas/candidate/retrieve_result.py
- lambdas/candidate/utils/request.py
> chore(candidate): clean up code in candidate lambda

- lambdas/company/me.py
- lambdas/company/utils/response.py
> chore(company): clean up code in company lambda

- .github/pull_request_template.md
- db/changelog/01-create-tables.sql
> fix(db): change db name candidate_result to interview

- lambdas/quiz/repo/quiz.py
- lambdas/quiz/retrieve.py
- lambdas/quiz/utils/request_parser.py
- web/src/screens/CreateAssessmentPage.tsx
- web/src/template/CreateAssessmentPage/CreateAssessmentPage.stories.tsx
- web/src/template/CreateAssessmentPage/CreateAssessmentPage.tsx
implemented web functionality as well
> feat(quiz): retrieve quizzes based on search keyword

- web/src/components/Avatar/Avatar.stories.tsx
- web/src/components/Avatar/Avatar.tsx
- web/src/components/DropdownMenu/UserNavDropdownMenu/UserNavDropdownMenu.stories.tsx
- web/src/template/CreateAssessmentPage/CreateAssessmentPage.tsx
- web/tailwind.config.ts
1. Show Skeleton while the name doesn't exist
a. Will need to update code when we decide to use images
2. Update `tailwind.config.ts` to extend animation rather than overriding it
3. Fix some `key` complaint from React in `CreateAssessmentPage.tsx`
Fixes #999
> feat(web): show skeleton while loading Avatar name
